Heroku/config/routes.rb
Rails.application.routes.draw do

  # Routes for Sessions Controller
  root "sessions#index"
  post '/sessions' => "sessions#create"
  delete '/logout' => "sessions#destroy"

  # Routes for Admins Controller
  resources :admins

  # Routes for Users Controller
  resources :users
end

Heroku/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Heroku/app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates_uniqueness_of :email
end

Heroku/app/controllers/admins_controller.rb
class AdminsController < ApplicationController

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @create_error
    user = User.new(user_params)
    if user.role == 'admin' && user.save
      redirect_to '/admins'
    elsif user.role == 'user' && user.save
      session[:id] = user.id
      redirect_to '/users/new'
    else
      @create_error = "Please enter valid credentials"
      render 'new'
    end
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to '/admins'
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :role)
  end

end

Heroku/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

Heroku/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def index
  end

  def create
    @login_error
    user = User.find_by_email(user_params[:email])
    if user && user.authenticate(user_params[:password])
      session[:type] = user.role
      if user.role == 'admin'
        redirect_to '/admins'
      else
        redirect_to user
      end
    else
      @login_error = "Invalid Credentials"
      render 'index'
    end
  end

  def destroy
    session[:type]=nil
    render 'index'
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end

end

Heroku/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @user = User.find(session[:id])
  end

  def new
    @user = User.find(session[:id])
  end

  def create
    @msg
    @user = User.find(session[:id])
    if dob?(params[:user][:datebirth])
        if @user.update(user_params)
          redirect_to @user
        else
          @msg="Invalid credentials"
          render 'index'
        end
    else
      @msg="Users above 18 years are only allowed"
      render 'index'
    end
  end

  def edit
    @user=User.find(params[:id])
  end

  def update
      @user=User.find(params[:id])
    if @user.update(user_params)
      redirect_to '/admins'
    end
  end

  def show
    @user=User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:fname,:lname,:datebirth,:datejoining,:sal,:contact,:bloodtype,:address,
    :city,:state,:country,:pincode,:gender,:ename,:relation,:econtact,:pskill,:sskill,:sskill2,:notice,:role)
  end

  def dob?(date)
    (((Date.today-date.to_date)/365).to_i>=18)
  end
end

Heroku/app/helpers/admins_helper.rb
module AdminsHelper
end

Heroku/app/helpers/application_helper.rb
module ApplicationHelper
end

Heroku/app/helpers/sessions_helper.rb
module SessionsHelper
end

Heroku/app/helpers/users_helper.rb
module UsersHelper
end

Heroku/app/views/admins/_form.html.erb
<form action="/admins" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <table class="w3-table w3-striped w3-border">
    <tr>
      <td colspan="4"><label><h4>LOGIN DETAILS</h4></label></td>
    </tr>
    <tr>
      <td><strong><label>Email</label></strong></td>
      <td><input type="email" name="user[email]"></td>
      <td><strong><label>Role</label></strong></td>
      <td><input type="radio" name="user[role]" value="user" checked> User
          <input type="radio" name="user[role]" value="admin"> Admin</td>
    </tr>
    <tr>
      <td><strong><label>Password</label></strong></td>
      <td><input type="password" name="user[password]"></td>
      <td><strong><label>Confirm Password</label></strong></td>
      <td><input type="password" name="user[password_confirmation]"></td>
    </tr>
  </table>
  <input type="submit" name="submit" value="Submit">
  <input type="reset" name="reset" value="Reset">
</form>

Heroku/app/views/admins/index.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://unpkg.com/purecss@1.0.1/build/pure-min.css" integrity="sha384-oAOxQR6DkCoMliIh8yFnu25d7Eq/PHS21PClpwjOTeU2jRSq11vu66rf90/cZr47" crossorigin="anonymous">
  </head>
  <body>
    <div class="header">
    <a class="logo" href="#"><img src="http://www.exalogic.in/wp-content/uploads/2018/08/exalogic.png" alt="Exalogic"></a>
    <div class="header-right">
      <a class="active" href="#">Home</a>
      <%= link_to "Create User", new_admin_path%>
      <%= link_to "Logout", logout_path, method: :delete, data: { confirm: 'Are you sure?' } %>
    </div>
    </div>
        <fieldset>
          <legend><strong><h3>USERS</h3></strong></legend>
          <table class="w3-table w3-striped w3-border">
            <thead>
              <th>First Name</th>
              <th>Last Name</th>
              <th>Email id</th>
              <th>Contact</th>
              <th>Primary Skill</th>
              <th></th>
              <th></th>
              <th></th>
            </thead>
            <% @users.each do |user|%>
              <% unless user.role=='admin' %>
                <tr>
                  <td><%= user.fname%></td>
                  <td><%= user.lname%></td>
                  <td><%= user.email%></td>
                  <td><%= user.contact.to_i%></td>
                  <td><%= user.pskill%></td>
                  <td><%= link_to "Show User", user, :class => "link"%></td>
                  <td><%= link_to "Edit User", edit_user_path(user), :class => "link"%></td>
                  <td><%= link_to "Delete User", admin_path(user), method: :delete, data: { confirm: "Are you sure?"}, :class => "link"%></td>
                </tr>
              <% end %>
            <% end %>
          </table>
        </fieldset>
        <fieldset>
          <legend><strong><h3>ADMINS</h3></strong></legend>
          <table class="pure-table pure-table-horizontal">
            <thead>
              <th>Email-id</th>
              <th></th>
              <th></th>
            </thead>
            <% @users.each do |user|%>
              <% if user.role=='admin' %>
                <tr>
                  <td><%= user.email%></td>
                  <td><%= link_to "Edit User", edit_admin_path(user), :class => "link"%></td>
                  <td><%= link_to "Delete User", admin_path(user), method: :delete, data: { confirm: "Are you sure?"}, :class => "link"%></td>
                </tr>
              <% end %>
            <% end %>
          </table>
        </fieldset>
  </body>
</html>

Heroku/app/views/admins/new.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Create Users</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
  </head>
  <body>
    <div class="header">
    <a class="logo" href="/admins"><img src="http://www.exalogic.in/wp-content/uploads/2018/08/exalogic.png" alt="Exalogic"></a>
    <div class="header-right">
      <a href="/admins">Home</a>
      <%= link_to "Create User", new_admin_path, :class => "active"%>
      <%= link_to "Logout", logout_path, method: :delete, data: { confirm: 'Are you sure?' } %>
    </div>
    </div>
    <fieldset>
      <legend><strong><h4>CREATE USERS</h4></strong></legend>
      <span><%= @create_error%></span>
      <%= render "form"%>
    </fieldset>
  </body>
</html>

Heroku/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Heroku</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

Heroku/app/views/users/edit.html.erb
<%= form_for @user do |f| %>
      <table class="w3-table w3-striped w3-border">
        <tr>
          <td><%= f.label "First Name"%></td>
          <td><%= f.text_field :fname%></td>
          <td><%= f.label "Last Name"%></td>
          <td><%= f.text_field :lname%></td>
        </tr>
        <tr>
          <td><%= f.label "Date of Birth"%></td>
          <td><%= f.date_field :datebirth%></td>
          <td><%= f.label "Date of Joining"%></td>
          <td><%= f.date_field :datejoining%></td>
        </tr>
        <tr>
            <td><%= f.label "Blood Type"%></td>
          <td><%= f.select :bloodtype, ['Blood Type','AB+','AB-','A+','A-','B+','B-','O+','O-']%></td>
          <td><%= f.label "Salary per annum"%></td>
          <td><%= f.number_field :sal, :min=>0%></td>
        </tr>
        <tr>
          <td><%= f.label :contact%></td>
          <td><%= f.text_field :contact, :pattern=>'\d*', :maxlength=>10, :minlength=>10%></td>
          <td><%= f.label "Gender"%></td>
          <td><%= f.select :gender, ['Gender','Male','Female']%></td>
        </tr>
        <tr>
          <td><%= f.label :address%></td>
          <td><%= f.text_area :address, :rows => 1%></td>
          <td><%= f.label :city%></td>
          <td><%= f.text_field :city%></td>
        </tr>
        <tr>
          <td><%= f.label :state%></td>
          <td><%= f.select :state, ['State','Andaman and Nicobar Islands','Andhra Pradesh','Arunachal Pradesh','Assam',
            'Bihar','Chandigarh','Chhattisgarh','Dadra and Nagar Haveli','Daman and Diu','Delhi','Goa','Gujarat','Haryana',
            'Himachal Pradesh','Jammu and Kashmir','Jharkhand','Karnataka','Kerala','Ladakh','Lakshadweep','Madhya Pradesh',
            'Maharashtra','Manipur','Meghalaya','Mizoram','Nagaland','Odisha','Puducherry','Punjab','Rajasthan','Sikkim','Tamil Nadu',
            'Telangana','Tripura','Uttar Pradesh','Uttarakhand','West Bengal']%></td>
          <td><%= f.label :country%></td>
          <td><%= f.select :country, ['Country','India']%></td>
        </tr>
        <tr>
          <td><%= f.label "Pincode"%></td>
          <td><%= f.text_field :pincode, :pattern=>'\d*', :maxlength=>6, :minlength=>6%></td>
          <td><%= f.label "Notice period in days"%></td>
          <td><%= f.number_field :notice, :min=>0%></td>
        </tr>
        <tr>
          <td><%= f.label "Emergency Contact Name"%></td>
          <td><%= f.text_field :ename%></td>
          <td><%= f.label "Relation"%></td>
          <td><%= f.select :relation, ['Relation','Parent','Spouse','Friend','Others']%></td>
        </tr>
        <tr>
          <td><%= f.label "Emergency Contact Number"%></td>
          <td><%= f.text_field :econtact, :pattern=>'\d*', :maxlength=>10, :minlength=>10%></td>
          <td><%= f.label "Primary Skill"%></td>
          <td><%= f.text_field :pskill%></td>
        </tr>
        <tr>
          <td><%= f.label "Secondary Skill 1"%></td>
          <td><%= f.text_field :sskill%></td>
          <td><%= f.label "Secondary Skill 2"%></td>
          <td><%= f.text_field :sskill2%></td>
        </tr>
        <tr>
          <td><%= f.submit%></td>
          <td></td>
          <td></td>
          <td></td>
        </tr>
      </table>
    <% end %>

Heroku/app/views/users/new.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <script type="text/javascript">
      function onlyAlphabets(e, t) {
          try {
              if (window.event) {
                  var charCode = window.event.keyCode;
              }
              else if (e) {
                  var charCode = e.which;
              }
              else { return true; }
              if ((charCode > 64 && charCode < 91) || (charCode > 96 && charCode < 123))
                  return true;
              else
                  return false;
          }
          catch (err) {
              alert(err.Description);
          }
      }
      function onlyNumbers(e, t) {
          try {
              if (window.event) {
                  var charCode = window.event.keyCode;
              }
              else if (e) {
                  var charCode = e.which;
              }
              else { return true; }
              if (charCode > 47 && charCode < 58)
                  return true;
              else
                  return false;
          }
          catch (err) {
              alert(err.Description);
          }
      }
    </script>
  </head>
  <body>
    <div class="header">
    <a class="logo" href="/admins"><img src="http://www.exalogic.in/wp-content/uploads/2018/08/exalogic.png" alt="Exalogic"></a>
    <div class="header-right">
      <a href="/admins">Home</a>
      <%= link_to "Create User", new_admin_path%>
      <%= link_to "Logout", logout_path, method: :delete, data: { confirm: 'Are you sure?' } %>
    </div>
    </div>
    <h3 style="text-align:center;"><strong>UPDATE USER DETAILS</strong></h3>
    <span><%= @msg%></span>
    <%= form_for @user do |f| %>
          <table class="w3-table w3-striped w3-border">
            <tr>
              <td><%= f.label "First Name"%></td>
              <td><%= f.text_field :fname%></td>
              <td><%= f.label "Last Name"%></td>
              <td><%= f.text_field :lname%></td>
            </tr>
            <tr>
              <td><%= f.label "Date of Birth"%></td>
              <td><%= f.date_field :datebirth%></td>
              <td><%= f.label "Date of Joining"%></td>
              <td><%= f.date_field :datejoining%></td>
            </tr>
            <tr>
                <td><%= f.label "Blood Type"%></td>
              <td><%= f.select :bloodtype, ['Blood Type','AB+','AB-','A+','A-','B+','B-','O+','O-']%></td>
              <td><%= f.label "Salary per annum"%></td>
              <td><%= f.number_field :sal, :min=>0%></td>
            </tr>
            <tr>
              <td><%= f.label :contact%></td>
              <td><%= f.text_field :contact, :pattern=>'\d*', :maxlength=>10, :minlength=>10%></td>
              <td><%= f.label "Gender"%></td>
              <td><%= f.select :gender, ['Gender','Male','Female']%></td>
            </tr>
            <tr>
              <td><%= f.label :address%></td>
              <td><%= f.text_area :address, :rows => 1%></td>
              <td><%= f.label :city%></td>
              <td><%= f.text_field :city%></td>
            </tr>
            <tr>
              <td><%= f.label :state%></td>
              <td><%= f.select :state, ['State','Andaman and Nicobar Islands','Andhra Pradesh','Arunachal Pradesh','Assam',
                'Bihar','Chandigarh','Chhattisgarh','Dadra and Nagar Haveli','Daman and Diu','Delhi','Goa','Gujarat','Haryana',
                'Himachal Pradesh','Jammu and Kashmir','Jharkhand','Karnataka','Kerala','Ladakh','Lakshadweep','Madhya Pradesh',
                'Maharashtra','Manipur','Meghalaya','Mizoram','Nagaland','Odisha','Puducherry','Punjab','Rajasthan','Sikkim','Tamil Nadu',
                'Telangana','Tripura','Uttar Pradesh','Uttarakhand','West Bengal']%></td>
              <td><%= f.label :country%></td>
              <td><%= f.select :country, ['Country','India']%></td>
            </tr>
            <tr>
              <td><%= f.label "Pincode"%></td>
              <td><%= f.text_field :pincode, :pattern=>'\d*', :maxlength=>6, :minlength=>6%></td>
              <td><%= f.label "Notice period in days"%></td>
              <td><%= f.number_field :notice, :min=>0%></td>
            </tr>
            <tr>
              <td><%= f.label "Emergency Contact Name"%></td>
              <td><%= f.text_field :ename%></td>
              <td><%= f.label "Relation"%></td>
              <td><%= f.select :relation, ['Relation','Parent','Spouse','Friend','Others']%></td>
            </tr>
            <tr>
              <td><%= f.label "Emergency Contact Number"%></td>
              <td><%= f.text_field :econtact, :pattern=>'\d*', :maxlength=>10, :minlength=>10%></td>
              <td><%= f.label "Primary Skill"%></td>
              <td><%= f.text_field :pskill%></td>
            </tr>
            <tr>
              <td><%= f.label "Secondary Skill 1"%></td>
              <td><%= f.text_field :sskill%></td>
              <td><%= f.label "Secondary Skill 2"%></td>
              <td><%= f.text_field :sskill2%></td>
            </tr>
            <tr>
              <td><%= f.submit%></td>
              <td></td>
              <td></td>
              <td></td>
            </tr>
          </table>
        <% end %>
  </body>
</html>

Heroku/app/views/users/show.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
  </head>
  <body>
    <div class="header">
      <% if session[:type]=='admin' %>
          <a class="logo" href="/admins"><img src="http://www.exalogic.in/wp-content/uploads/2018/08/exalogic.png" alt="Exalogic"></a>
          <div class="header-right">
          <a href="/admins">Home</a>
          <%= link_to "Create User", new_admin_path%>
      <% else %>
          <a class="logo" href="#"><img src="http://www.exalogic.in/wp-content/uploads/2018/08/exalogic.png" alt="Exalogic"></a>
          <div class="header-right">
          <a href="#" class="active">Home</a>
      <% end %>
      <%= link_to "Logout", logout_path, method: :delete, data: { confirm: 'Are you sure?' } %>
    </div>
    </div>
      <fieldset>
        <legend><strong>USER DETAILS</strong></legend>
        <table class="w3-table w3-striped w3-border">
          <tr>
            <td><b>First Name</b></td>
            <td><%= @user.fname%></td>
            <td><b>Last Name</b></td>
            <td><%= @user.lname%></td>
          </tr>
          <tr>
            <td><b>Date of Birth</b></td>
            <td><%= @user.datebirth%></td>
            <td><b>Age</b></td>
            <td><span><%= ((Date.today-@user.datebirth.to_date)/365).to_i%></span></td>
          </tr>
          <tr>
            <td><b>Date of Joining</b></td>
            <td><%= @user.datejoining%></td>
            <td><b>Blood Type</b></td>
            <td><%= @user.bloodtype%></td>
          </tr>
          <tr>
            <td><b>Salary per annum</b></td>
            <% unless @user.sal==nil%>
              <td><%= @user.sal.to_i%></td>
            <% else%>
              <td></td>
            <% end%>
            <td><b>Salary per month</b></td>
            <td><span><%= (@user.sal/12).to_i%></span></td>
          </tr>
          <tr>
            <td><b>Contact</b></td>
            <% unless @user.contact==nil%>
              <td><%= @user.contact%></td>
            <% else%>
              <td></td>
            <% end%>
            <td><b>Email</b></td>
            <td><%= @user.email%></td>
          </tr>
          <tr>
            <td><b>Address</b></td>
            <td><%= @user.address%></td>
            <td><b>City</b></td>
            <td><%= @user.city%></td>
          </tr>
          <tr>
            <td><b>State</b></td>
            <td><%= @user.state%></td>
            <td><b>Country</b></td>
            <td><%= @user.country%></td>
          </tr>
          <tr>
            <td><b>Pincode</b></td>
            <% unless @user.pincode==nil%>
              <td><%= @user.pincode.to_i%></td>
            <% else%>
              <td></td>
            <% end%>
            <td><b>Gender</b></td>
            <td><%= @user.gender%></td>
          </tr>
          <tr>
            <td><b>Emergency Contact Name</b></td>
            <td><%= @user.ename%></td>
            <td><b>Relation</b></td>
            <td><%= @user.relation%></td>
          </tr>
          <tr>
            <td><b>Emergency Contact Number</b></td>
            <% unless @user.econtact==nil%>
              <td><%= @user.econtact%></td>
            <% else%>
              <td></td>
            <% end%>
            <td><b>Primary Skill</b></td>
            <td><%= @user.pskill%></td>
          </tr>
          <tr>
            <td><b>Secondary Skill 1</b></td>
            <td><%= @user.sskill%></td>
            <td><b>Secondary Skill 2</b></td>
            <td><%= @user.sskill2%></td>
          </tr>
          <tr>
            <td><b>Notice period in days</b></td>
            <% unless @user.notice==nil%>
              <td><%= @user.notice.to_i%></td>
            <% else%>
              <td></td>
            <% end%>
            <td></td>
            <td></td>
          </tr>
        </table>
        <% if session[:type]=='admin' %>
            <%= link_to "Edit User", edit_user_path(@user), :class => 'link'%>
        <% end %>
      </fieldset>
  </body>
</html>