Project/config/routes.rb
Rails.application.routes.draw do
  root "sessions#index"
  resources :users
  resources :admins, only: [:index, :create]
  resources :sessions, only: [:index, :create]
  get '/home' => "home#index"
  delete '/logout' => "admins#destroy", as: 'logout'
end

Project/app/models/admin.rb
class Admin < ApplicationRecord
  has_secure_password
end

Project/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Project/app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

Project/app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  def index
  end

  def create
    @error2
    admin = Admin.find_by_email(adminparams[:email])
    if admin && admin.authenticate(adminparams[:password])
      session[:user_type]='admin'
      redirect_to '/users'
    else
      @error2='Invalid Email-id/Password'
      render 'index'
    end
  end

  def destroy
    session[:user_type] = nil
    redirect_to root_path
  end

  private

  def adminparams
    params.require(:admin).permit(:email,:password)
  end
end

Project/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

Project/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def index
  end

  def create
    @error1
    @user = User.find_by_email(userparams[:email])
    if @user && @user.authenticate(userparams[:password])
      session[:user_id]=@user.id
      redirect_to @user
    else
      @error1='Invalid Email-id/Password'
      render 'index'
    end
  end

  private

  def userparams
    params.require(:user).permit(:email,:password)
  end
end

Project/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, except: [:index, :create, :new]
  before_action :is_admin?, except: [:show]
  before_action :is_user?, only: [:show]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @error3
    @user = User.new(user_params)
    if @user.save
      redirect_to @user
    else
      @error3='Please enter proper Email-id and Password'
      render 'new'
    end
  end

  def edit
  end

  def update
    @error4
    if @user.update(user_params)
      redirect_to @user
    else
      @error4='Please enter proper Email-id and Password'
      render 'edit'
    end
  end

  def show
  end

  def destroy
    @user.destroy
    redirect_to '/users'
  end

  private

  def find_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:fname,:lname,:datebirth,:datejoining,:age,:sal,:salpm,:contact,:bloodtype,
    :address,:city,:state,:country,:pincode,:gender,:ename,:relation,:econtact,:pskill,:sskill,:sskill2,
    :notice,:email,:password,:password_confirmation)
  end

  def is_admin?
    if session[:user_type]!='admin'
      redirect_to root_path
    end
  end

  def is_user?
    unless session[:user_id]==@user.id || session[:user_type]=='admin'
      redirect_to root_path
    end
  end
end

Project/app/helpers/admins_helper.rb
module AdminsHelper
end

Project/app/helpers/application_helper.rb
module ApplicationHelper
end

Project/app/helpers/sessions_helper.rb
module SessionsHelper
end

Project/app/helpers/users_helper.rb
module UsersHelper
end

Project/app/views/admins/index.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Admin Login</title>
    <style type="text/css">
        .my_centered_buttons { display: flex; justify-content: center; }
    </style>
  </head>
  <body>
    <div class="forms">
        <ul class="tab-group">
            <li class="tab"><a href="/">Users</a></li>
            <li class="tab active"><a href="/admins">Admins</a></li>
        </ul>
        <form action="/admins" method="post">
              <h1>Login</h1>
              <div class="input-field">
                <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
                <label for="email">Email</label>
                <input type="email" name="admin[email]" required="email" />
                <label for="password">Password</label>
                <input type="password" name="admin[password]" required/>
                <span><%= @error2%></span>
                <input type="submit" value="Login" class="button"/>
              </div>
          </form>
    </div>
  </body>
</html>

Project/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

Project/app/views/users/_form.html.erb
<%= form_for @user do |f|%>
<span><%= @create_error%></span>
<table class="w3-table w3-striped w3-border">
  <tr>
    <td><%= f.label "First Name"%></td>
    <td><%= f.text_field :fname%></td>
    <td><%= f.label "Last Name"%></td>
    <td><%= f.text_field :lname%></td>
  </tr>
  <tr>
    <td><%= f.label "Date of Birth"%></td>
    <td><%= f.date_field :datebirth%></td>
    <td><%= f.label :age%></td>
    <td><%= f.number_field :age%></td>

  </tr>
  <tr>
    <td><%= f.label "Date of Joining"%></td>
    <td><%= f.date_field :datejoining%></td>
    <td><%= f.label "Blood Type"%></td>
    <td><%= f.select :bloodtype, ['AB+','AB-','A+','A-','B+','B-','O+','O-']%></td>
  </tr>
  <tr>
    <td><%= f.label "Salary per annum"%></td>
    <td><%= f.number_field :sal%></td>
    <td><%= f.label "Salary per month"%></td>
    <td><%= f.number_field :salpm%></td>
  </tr>
  <tr>
    <td><%= f.label :contact%></td>
    <td><%= f.number_field :contact%></td>
    <td><%= f.label "Gender"%></td>
    <td><%= f.select :gender, ['Male','Female']%></td>
  </tr>
  <tr>
    <td><%= f.label :address%></td>
    <td><%= f.text_area :address, :rows => 1%></td>
    <td><%= f.label :city%></td>
    <td><%= f.text_field :city%></td>
  </tr>
  <tr>
    <td><%= f.label :state%></td>
    <td><%= f.text_field :state%></td>
    <td><%= f.label :country%></td>
    <td><%= f.select :country, ['India']%></td>
  </tr>
  <tr>
    <td><%= f.label "Pincode"%></td>
    <td><%= f.number_field :pincode%></td>
    <td><%= f.label "Notice period in days"%></td>
    <td><%= f.number_field :notice%></td>
  </tr>
  <tr>
    <td><%= f.label "Emergency Contact Name"%></td>
    <td><%= f.text_field :ename%></td>
    <td><%= f.label "Relation"%></td>
    <td><%= f.select :relation, ['Parent','Spouse','Friend','Others']%></td>
  </tr>
  <tr>
    <td><%= f.label "Emergency Contact Number"%></td>
    <td><%= f.number_field :econtact%></td>
    <td><%= f.label "Primary Skill"%></td>
    <td><%= f.text_field :pskill%></td>
  </tr>
  <tr>
    <td><%= f.label "Secondary Skill 1"%></td>
    <td><%= f.text_field :sskill%></td>
    <td><%= f.label "Secondary Skill 2"%></td>
    <td><%= f.text_field :sskill2%></td>
  </tr>
  <tr>
    <td colspan="4"><label><h3><b>LOGIN DETAILS</b></h3></label></td>
  </tr>
  <tr>
    <td><%= f.label :email%></td>
    <td><%= f.email_field :email%></td>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <td><%= f.label :password%></td>
    <td><%= f.password_field :password%></td>
    <td><%= f.label :"Confirm Password"%></td>
    <td><%= f.password_field :password_confirmation%></td>
  </tr>
  <tr>
    <td><%= f.submit%></td>
    <td></td>
    <td></td>
    <td></td>
  </tr>
</table>
<% end%>

Project/app/views/users/edit.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Create Users</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
  </head>
  <body>
    <div class="header">
    <a class="logo" href="/users"><img src="http://www.exalogic.in/wp-content/uploads/2018/08/exalogic.png" alt="Exalogic"></a>
    <div class="header-right">
      <a href="/users">Home</a>
      <%= link_to "Create User", new_user_path%>
      <%= link_to "Logout", logout_path, method: :delete, data: { confirm: 'Are you sure?' } %>
    </div>
    </div>
    <fieldset>
      <legend><strong><h4>EDIT USERS</h4></strong></legend>
      <span><%= @error4%></span>
      <%= render "form"%>
    </fieldset>
  </body>
</html>

Project/app/views/users/index.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
  </head>
  <body>
    <div class="header">
    <a class="logo" href="#"><img src="http://www.exalogic.in/wp-content/uploads/2018/08/exalogic.png" alt="Exalogic"></a>
    <div class="header-right">
      <a class="active" href="#">Home</a>
      <%= link_to "Create User", new_user_path%>
      <%= link_to "Logout", logout_path, method: :delete, data: { confirm: 'Are you sure?' } %>
    </div>
    </div>
        <fieldset>
          <legend><strong><h3>ALL USERS</h3></strong></legend>
          <table class="w3-table w3-striped w3-border">
            <thead>
              <th>First Name</th>
              <th>Last Name</th>
              <th>Email id</th>
              <th>Contact</th>
              <th>Primary Skill</th>
              <th></th>
              <th></th>
              <th></th>
            </thead>
            <% @users.each do |user|%>
              <tr>
                <td><%= user.fname%></td>
                <td><%= user.lname%></td>
                <td><%= user.email%></td>
                <td><%= user.contact.to_i%></td>
                <td><%= user.pskill%></td>
                <td><%= link_to "Show User", user, :class => "link"%></td>
                <td><%= link_to "Edit User", edit_user_path(user), :class => "link"%></td>
                <td><%= link_to "Delete User", user_path(user), method: :delete, data: { confirm: "Are you sure?"}, :class => "link"%></td>
              </tr>
            <% end %>
          </table>
        </fieldset>
  </body>
</html>

Project/app/views/users/new.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Create Users</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
  </head>
  <body>
    <div class="header">
    <a class="logo" href="/users"><img src="http://www.exalogic.in/wp-content/uploads/2018/08/exalogic.png" alt="Exalogic"></a>
    <div class="header-right">
      <a href="/users">Home</a>
      <%= link_to "Create User", new_user_path, :class => "active"%>
      <%= link_to "Logout", logout_path, method: :delete, data: { confirm: 'Are you sure?' } %>
    </div>
    </div>
    <fieldset>
      <legend><strong><h4>CREATE USERS</h4></strong></legend>
      <span><%= @error3%></span>
      <%= render "form"%>
    </fieldset>
  </body>
</html>

Project/app/views/users/show.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
  </head>
  <body>
    <div class="header">
      <% if session[:user_type]=='admin' %>
          <a class="logo" href="/users"><img src="http://www.exalogic.in/wp-content/uploads/2018/08/exalogic.png" alt="Exalogic"></a>
          <div class="header-right">
          <a href="/users">Home</a>
          <%= link_to "Create User", new_user_path%>
      <% else %>
          <a class="logo" href="#"><img src="http://www.exalogic.in/wp-content/uploads/2018/08/exalogic.png" alt="Exalogic"></a>
          <div class="header-right">
          <a href="#" class="active">Home</a>
      <% end %>
      <%= link_to "Logout", logout_path, method: :delete, data: { confirm: 'Are you sure?' } %>
    </div>
    </div>
      <fieldset>
        <legend><strong>USER DETAILS</strong></legend>
        <table class="w3-table w3-striped w3-border">
          <tr>
            <td><b>First Name</b></td>
            <td><%= @user.fname%></td>
            <td><b>Last Name</b></td>
            <td><%= @user.lname%></td>
          </tr>
          <tr>
            <td><b>Date of Birth</b></td>
            <td><%= @user.datebirth%></td>
            <td><b>Age</b></td>
            <td><%= @user.age.to_i%></td>
          </tr>
          <tr>
            <td><b>Date of Joining</b></td>
            <td><%= @user.datejoining%></td>
            <td><b>Blood Type</b></td>
            <td><%= @user.bloodtype%></td>
          </tr>
          <tr>
            <td><b>Salary per annum</b></td>
            <td><%= @user.sal%></td>
            <td><b>Salary per month</b></td>
            <td><%= @user.salpm%></td>
          </tr>
          <tr>
            <td><b>Contact</b></td>
            <td><%= @user.contact.to_i%></td>
            <td><b>Email</b></td>
            <td><%= @user.email%></td>
          </tr>
          <tr>
            <td><b>Address</b></td>
            <td><%= @user.address%></td>
            <td><b>City</b></td>
            <td><%= @user.city%></td>
          </tr>
          <tr>
            <td><b>State</b></td>
            <td><%= @user.state%></td>
            <td><b>Country</b></td>
            <td><%= @user.country%></td>
          </tr>
          <tr>
            <td><b>Pincode</b></td>
            <td><%= @user.pincode.to_i%></td>
            <td><b>Gender</b></td>
            <td><%= @user.gender%></td>
          </tr>
          <tr>
            <td><b>Emergency Contact Name</b></td>
            <td><%= @user.ename%></td>
            <td><b>Relation</b></td>
            <td><%= @user.relation%></td>
          </tr>
          <tr>
            <td><b>Emergency Contact Number</b></td>
            <td><%= @user.econtact.to_i%></td>
            <td><b>Primary Skill</b></td>
            <td><%= @user.pskill%></td>
          </tr>
          <tr>
            <td><b>Secondary Skill 1</b></td>
            <td><%= @user.sskill%></td>
            <td><b>Secondary Skill 2</b></td>
            <td><%= @user.sskill2%></td>
          </tr>
          <tr>
            <td><b>Notice period in days</b></td>
            <td><%= @user.notice.to_i%></td>
            <td></td>
            <td></td>
          </tr>
        </table>
        <% if session[:user_type]=='admin' %>
            <%= link_to "Edit User", edit_user_path(@user), :class => 'link'%>
        <% end %>
      </fieldset>
  </body>
</html>